dist: xenial
language: python

branches:
  only:
  - master

env:
  - DEPS=""
  - DEPS="lxml"

python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - 3.9-dev

install:
  - pip install numpy
  # only install deps if the $DEPS variable is not empty
  # -z returns true on empty string
  - if [[ ! -z "$DEPS" ]]; then pip install $DEPS; fi;
  - python setup.py install

script: python collada
